/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayPauseFrame.java
 *
 * Created on 09.08.2013, 20:40:57
 */
package userinterface;

import javax.swing.border.TitledBorder;

/**
 *
 * @author christoph
 */
public class AnimationFrame extends javax.swing.JFrame {

    Board boardPanel;
    EditorFrame parent;
    
    /** Creates new form PlayPauseFrame */
    public AnimationFrame() {
        initComponents();
    }

    public AnimationFrame(Board pnl, EditorFrame frame) {
        initComponents();
        boardPanel = pnl;
        parent = frame;
        setLocation(frame.getLocation().x + frame.getWidth(), frame.getLocation().y + frame.getHeight() - 400);
        setTitle("sidebar");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_move_controls = new javax.swing.JPanel();
        pnl_start = new ImagePanel("start_button");
        pnl_stop = new ImagePanel("stop_button");
        pnl_pause = new ImagePanel("pause_button");
        pnl_speed = new javax.swing.JPanel();
        sld_speed = new javax.swing.JSlider();

        setTitle("animation");
        getContentPane().setLayout(new java.awt.GridLayout(2, 0));

        pnl_move_controls.setBackground(new java.awt.Color(-1,true));
        pnl_move_controls.setBorder(javax.swing.BorderFactory.createTitledBorder("start/stop/pause animation"));
        pnl_move_controls.setToolTipText("");
        pnl_move_controls.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        pnl_start.setBackground(new java.awt.Color(-1,true));
        pnl_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onStartClick(evt);
            }
        });

        javax.swing.GroupLayout pnl_startLayout = new javax.swing.GroupLayout(pnl_start);
        pnl_start.setLayout(pnl_startLayout);
        pnl_startLayout.setHorizontalGroup(
            pnl_startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );
        pnl_startLayout.setVerticalGroup(
            pnl_startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        pnl_move_controls.add(pnl_start);

        pnl_stop.setBackground(new java.awt.Color(-1,true));
        pnl_stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onStopClick(evt);
            }
        });

        javax.swing.GroupLayout pnl_stopLayout = new javax.swing.GroupLayout(pnl_stop);
        pnl_stop.setLayout(pnl_stopLayout);
        pnl_stopLayout.setHorizontalGroup(
            pnl_stopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );
        pnl_stopLayout.setVerticalGroup(
            pnl_stopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        pnl_move_controls.add(pnl_stop);

        pnl_pause.setBackground(new java.awt.Color(-1,true));
        pnl_pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onPauseClick(evt);
            }
        });

        javax.swing.GroupLayout pnl_pauseLayout = new javax.swing.GroupLayout(pnl_pause);
        pnl_pause.setLayout(pnl_pauseLayout);
        pnl_pauseLayout.setHorizontalGroup(
            pnl_pauseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );
        pnl_pauseLayout.setVerticalGroup(
            pnl_pauseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        pnl_move_controls.add(pnl_pause);

        getContentPane().add(pnl_move_controls);

        pnl_speed.setBackground(new java.awt.Color(-1,true));
        pnl_speed.setBorder(javax.swing.BorderFactory.createTitledBorder("animation speed (in milliseconds)"));
        pnl_speed.setLayout(new java.awt.GridLayout());

        sld_speed.setMaximum(3000);
        sld_speed.setMinimum(10);
        sld_speed.setValue(70);
        sld_speed.setBorder(javax.swing.BorderFactory.createTitledBorder("70"));
        sld_speed.setInverted(true);
        sld_speed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                onChangeSlider(evt);
            }
        });
        pnl_speed.add(sld_speed);

        getContentPane().add(pnl_speed);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void onStartClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onStartClick
    boardPanel.restart();
}//GEN-LAST:event_onStartClick

private void onStopClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onStopClick
// TODO add your handling code here:
}//GEN-LAST:event_onStopClick

private void onPauseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onPauseClick
    boardPanel.pause();
}//GEN-LAST:event_onPauseClick

private void onChangeSlider(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_onChangeSlider
    int value = sld_speed.getValue();
    sld_speed.setBorder(new TitledBorder("" + value));
    boardPanel.setDELAY(value);
}//GEN-LAST:event_onChangeSlider

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AnimationFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnl_move_controls;
    private javax.swing.JPanel pnl_pause;
    private javax.swing.JPanel pnl_speed;
    private javax.swing.JPanel pnl_start;
    private javax.swing.JPanel pnl_stop;
    private javax.swing.JSlider sld_speed;
    // End of variables declaration//GEN-END:variables
}
