/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrameGUI.java
 *
 * Created on 04.08.2013, 18:06:53
 */
package userinterface;

import blocktypes.*;
import plox.Level;

/**
 *
 * @author christoph
 */
public class EditorFrame extends PloxFrame {

    private Board boardPanel;
    private SidebarFrame sf;
    private AnimationFrame ppf;
    private GridFrame gf;
    private BlockFrame bf;
    private int drawMode = NO_DRAW;
    
    public static final int NO_DRAW = -1;
    public static final int PLAYER_DRAW = 0;
    public static final int STATIC_DRAW = 1;
    public static final int MOVE_DRAW = 2;
    public static final int FADE_DRAW = 3;
    public static final int SELF_MOVE_DRAW = 4;
    
    /** Creates new form FrameGUI */
    public EditorFrame() {
        initComponents();
        setTitle("PLOX");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setSize(700, 700);
        pnl_board.repaint();
        boardPanel = (Board) pnl_board;
        sf = new SidebarFrame(boardPanel, this);
        sf.setVisible(true);
        sf.setAlwaysOnTop(true);
        ppf = new AnimationFrame(boardPanel, this);
        ppf.setVisible(true);
        ppf.setAlwaysOnTop(true);
        gf = new GridFrame(boardPanel, this);
        gf.setVisible(true);
        gf.setAlwaysOnTop(true);
        bf = new BlockFrame(boardPanel, this);
        bf.setVisible(true);
        bf.setAlwaysOnTop(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_board = pnl_board = new Board(new Level(30, 30), this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(-1,true));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnl_board.setBackground(new java.awt.Color(-1,true));
        pnl_board.setName("pnl_board"); // NOI18N
        pnl_board.setRequestFocusEnabled(false);
        pnl_board.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boardMouseClicked(evt);
            }
        });
        pnl_board.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                boardMouseMoved(evt);
            }
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                boardMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout pnl_boardLayout = new javax.swing.GroupLayout(pnl_board);
        pnl_board.setLayout(pnl_boardLayout);
        pnl_boardLayout.setHorizontalGroup(
            pnl_boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );
        pnl_boardLayout.setVerticalGroup(
            pnl_boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_board);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void boardMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardMouseMoved
    if(drawMode == PLAYER_DRAW)
    {
    int res = boardPanel.getResolution();
    boardPanel.setPlayerPosition(evt.getX()/res, evt.getY()/res);
    }
}//GEN-LAST:event_boardMouseMoved

private void boardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardMouseClicked
    int res = boardPanel.getResolution();
    int x = evt.getX();
    int y = evt.getY();
    Level lvl = boardPanel.getLevel();
    
    switch(drawMode)
    {
        case PLAYER_DRAW: drawMode = NO_DRAW;break;
        case STATIC_DRAW: lvl.addBlock(new StaticBlock(x/res, y/res, lvl));break;
        case MOVE_DRAW: lvl.addBlock(new MoveBlock(x/res, y/res, lvl));break;
        case FADE_DRAW: lvl.addBlock(new StaticBlock(x/res, y/res, lvl));break;
        case SELF_MOVE_DRAW: lvl.addBlock(new StaticBlock(x/res, y/res, lvl));break;
    }
    
}//GEN-LAST:event_boardMouseClicked

private void boardMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardMouseDragged
    int res = boardPanel.getResolution();
    int x = evt.getX();
    int y = evt.getY();
    Level lvl = boardPanel.getLevel();
    
    switch(drawMode)
    {
        case PLAYER_DRAW: drawMode = NO_DRAW;break;
        case STATIC_DRAW: lvl.addBlock(new StaticBlock(x/res, y/res, lvl));break;
        case MOVE_DRAW: lvl.addBlock(new MoveBlock(x/res, y/res, lvl));break;
        case FADE_DRAW: lvl.addBlock(new StaticBlock(x/res, y/res, lvl));break;
        case SELF_MOVE_DRAW: lvl.addBlock(new StaticBlock(x/res, y/res, lvl));break;
    }
}//GEN-LAST:event_boardMouseDragged



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EditorFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnl_board;
    // End of variables declaration//GEN-END:variables

    @Override
    public int getResolutionX() {
        return pnl_board.getWidth();
    }
    
    @Override
    public int getResolutionY() {
        return pnl_board.getHeight();
    }

    public void setDrawMode(int mode)
    {
       drawMode = mode; 
    }
    
    public void showGrid()
    {
        boardPanel.setDrawGrid(true);
    }
    
    public void hideGrid()
    {
        boardPanel.setDrawGrid(false);
    }
}
