/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GridFrame.java
 *
 * Created on 09.08.2013, 20:55:53
 */
package userinterface;

/**
 *
 * @author christoph
 */
public class GridFrame extends javax.swing.JFrame {

    Board boardPanel;
    EditorFrame parent;
    
    /** Creates new form GridFrame */
    public GridFrame() {
        initComponents();
    }
    
    public GridFrame(Board pnl, EditorFrame frame) {
        initComponents();
        boardPanel = pnl;
        parent = frame;
        setLocation(frame.getLocation().x + frame.getWidth(), frame.getLocation().y );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp = new javax.swing.ButtonGroup();
        pnl_visibility = new javax.swing.JPanel();
        rbtShow = new javax.swing.JRadioButton();
        rbtHide = new javax.swing.JRadioButton();

        setTitle("grid options");
        getContentPane().setLayout(new java.awt.GridLayout());

        pnl_visibility.setBorder(javax.swing.BorderFactory.createTitledBorder("visibility"));
        pnl_visibility.setLayout(new java.awt.GridLayout(2, 0));

        btnGrp.add(rbtShow);
        rbtShow.setSelected(true);
        rbtShow.setText("show grid");
        rbtShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onShowClick(evt);
            }
        });
        pnl_visibility.add(rbtShow);

        btnGrp.add(rbtHide);
        rbtHide.setText("hide grid");
        rbtHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onHideClick(evt);
            }
        });
        pnl_visibility.add(rbtHide);

        getContentPane().add(pnl_visibility);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void onShowClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onShowClick
    parent.showGrid();
}//GEN-LAST:event_onShowClick

private void onHideClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onHideClick
    parent.hideGrid();
}//GEN-LAST:event_onHideClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GridFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GridFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GridFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GridFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GridFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrp;
    private javax.swing.JPanel pnl_visibility;
    private javax.swing.JRadioButton rbtHide;
    private javax.swing.JRadioButton rbtShow;
    // End of variables declaration//GEN-END:variables
}
